name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  ci:
    if: startsWith(github.ref, 'refs/tags/')
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Build
      run: cargo build --all --release
    - name: Test
      run: cargo test
    - name: Check documentation
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --workspace --all-features --no-deps --document-private-items
